import { useParams } from 'react-router-dom'
import { formatCurrency } from '../utils/currency.js'

function ProductDetailPage({ products, onAddToCart }) {
  const { slug } = useParams()
  const product = products.find((item) => String(item.id) === slug || item.title.toLowerCase().replaceAll(' ', '-') === slug)
  if (!product) return <main className="mx-auto max-w-7xl px-5 py-20 text-center"><h1 className="text-3xl font-bold">Product not found</h1><a className="mt-4 inline-block font-bold text-blue-700" href="/shop">Return to shop</a></main>
  return <main className="mx-auto max-w-7xl px-5 py-14 sm:px-8"><a className="text-sm font-bold text-blue-700" href="/shop">← Back to shop</a><div className="mt-8 grid gap-10 lg:grid-cols-2"><div className="grid grid-cols-2 gap-3">{(product.images?.slice(0, 4) || [product.thumbnail]).map((image) => <img className="aspect-square w-full rounded-2xl bg-slate-100 object-cover" src={image} alt={product.title} key={image} />)}</div><div className="self-center"><p className="text-sm font-bold uppercase tracking-[0.2em] text-blue-700">{product.category}</p><h1 className="mt-3 text-5xl font-bold tracking-tight text-blue-950">{product.title}</h1><div className="mt-5 flex items-center gap-2 text-sm text-slate-500">★ <strong className="text-slate-800">{product.rating.toFixed(1)}</strong> · {product.reviews?.length || 0} reviews</div><p className="mt-6 text-3xl font-bold text-blue-700">{formatCurrency(product.price)}</p><p className="mt-6 leading-7 text-slate-600">{product.description}</p><div className="mt-8 grid grid-cols-2 gap-3"><label className="text-xs font-bold uppercase tracking-wider text-slate-400">Size<select className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm text-slate-900"><option>S</option><option>M</option><option>L</option></select></label><label className="text-xs font-bold uppercase tracking-wider text-slate-400">Color<select className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm text-slate-900"><option>Cloud</option><option>Ink</option><option>Mint</option></select></label></div><p className="mt-5 text-sm font-bold text-emerald-700">{product.stock} in stock · Ready to ship</p><button className="mt-6 h-13 w-full rounded-xl bg-blue-950 py-4 text-sm font-bold text-white hover:bg-blue-800" type="button" onClick={() => onAddToCart(product)}>Add to cart</button></div></div></main>
}

export default ProductDetailPage
